---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "canary-demo.name" . }}
  namespace: {{ .Chart.Name }}
  labels:
    app: {{ include "canary-demo.name" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  port:
    targetPort: {{ .Values.service.targetPort }}
  to:
    kind: {{ .Values.route.kind }}
    name: {{ include "canary-demo.name" . }}
    weight: {{ .Values.route.weight }}
  wildcardPolicy: {{ .Values.route.wildcardPolicy | default "none" }}